### PR TITLE
docker dev environment

### PR DESCRIPTION
**Pull request by ludnic**
Share a reproducible dev environment in a dockerfile. 

With gfortran-11, fpm, vscode extensions and minimal footprint. 

Unfortunately with this setup (M1 MacBook running an ubuntu dev environment) the precompiled `libduckdb.so` doesn't seem to work and building it from source doesn't seem very straightforward. 

```shell
root@bcd976bae442:/workspaces/duckdb# fpm build  
 + mkdir -p build/dependencies
common.f90                             done.
test.c                                 done.
duckdb.f90                             done.
libduckdb.a                            done.
main.f90                               done.
main                                   failed.
[ 85%] Compiling...
/usr/bin/ld: skipping incompatible /usr/local/lib/libduckdb.so when searching for -lduckdb
/usr/bin/ld: cannot find -lduckdb: No such file or directory
/usr/bin/ld: skipping incompatible /usr/local/lib/libduckdb.so when searching for -lduckdb```

### CODE REVIEW

**Comment by lucin81** [comment]
@freevryheid there is actually no need to merge this, I meant to open against the fork but will leave it here in case you have a similar setup. 

I've taken your initial setup and can compile but not link so far. Will look further into it.

**Comment by freevryheid** [comment]
just for interest - can you compile against the macos lib?

**Comment by lucin81** [comment]
I tried that initially but the macOS lib doesn't blend well with the other linux tools in the container. maybe I need to spend a bit more time on it when I get a chance. but I think at first try the extension .dynlib was just not being picked up at all. 

sure would be nice to be able to build and run.

**Comment by freevryheid** [comment]
I'm on a virtual box with low mem. Tried compiling but ran into issues. These are the linux dependencies on the pre-built lib - nothing out of the ordinary:

[grassy@scp lib]$ ldd libduckdb.so
        linux-vdso.so.1 (0x00007ffdf3962000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f44af54b000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f44af546000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f44ac800000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f44af45e000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f44af43e000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f44ac619000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f44af55a000)

**Comment by lucin81** [comment]
I've sorted out the dev environment and duckdb at least. It is possible to force the container to emulate a different architecture and using linux/amd64 works with the shared object. 

Now that I could run the tests will send a quick fix and add more

**Pull request closed without merging**
